name: Modify and Release Python Wheels

on:
  workflow_dispatch:

jobs:
  modify-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install wheel and pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install wheel pip-tools

      - name: Download latest wheel for the package
        run: |
          pip download --no-deps --only-binary=:all: pyqt6 --dest wheels

      - name: Unpack the wheels
        run: |
          mkdir unpacked_wheels
          for wheel in wheels/*.whl; do
            unzip $wheel -d unpacked_wheels/$(basename $wheel .whl)
          done

      - name: Remove dependency from wheels
        run: |
          for metafile in unpacked_wheels/*/*.dist-info/METADATA; do
            sed -i '/Requires-Dist: PyQt6-Qt6 .*/d' $metafile
          done

      - name: Repack the wheels
        run: |
          mkdir modified_wheels
          for dir in unpacked_wheels/*; do
            python -m wheel pack $dir -d modified_wheels
          done

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: modified_wheels/*.whl
          tag_name: ${{ github.run_id }}

      - name: Cleanup
        run: |
          rm -rf wheels unpacked_wheels modified_wheels
