name: Modify and Release Python Wheels

on:
  workflow_dispatch:

jobs:
  modify:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install wheel and pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install wheel pip-tools

      - name: Download latest wheel for the package
        run: |
          # native Linux platform
          pip download --no-deps --only-binary=:all: pyqt6 --dest wheels
          # non-Linux platforms
          for platform in win_amd64 macosx_10_14_universal2; do
            pip download --no-deps --platform $platform --only-binary=:all: pyqt6 --dest wheels
          done

      - name: Unpack the wheels
        run: |
          mkdir unpacked_wheels
          for wheel in wheels/*.whl; do
            unzip $wheel -d unpacked_wheels/$(basename $wheel .whl)
          done

      - name: Remove Qt6 dependency from wheels
        run: |
          for metafile in unpacked_wheels/*/*.dist-info/METADATA; do
            sed -i '/Requires-Dist: PyQt6-Qt6 .*/d' $metafile
          done

      - name: Rename the package to pyqt6-without-qt
        run: |
          for metafile in unpacked_wheels/*/*.dist-info/METADATA; do
            sed -i 's/Name: PyQt6/Name: pyqt6-without-qt/' $metafile
          done

      - name: Repack the wheels
        run: |
          mkdir modified_wheels
          for dir in unpacked_wheels/*; do
            python -m wheel pack $dir -d modified_wheels
          done

      - name: Rename the repacked wheels to pyqt6-without-qt
        run: |
          for wheel in modified_wheels/*.whl; do
            mv $wheel $(echo $wheel | sed 's/PyQt6/pyqt6_without_qt/')
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: modified_wheels
          path: modified_wheels

  publish:
    needs: modify
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Download modified wheels
        uses: actions/download-artifact@v2
        with:
          name: modified_wheels
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.8.14
