name: Modify and Release Python Wheels

on:
  workflow_dispatch:

# Define a variable for post release
env:
  POST_RELEASE_SUFFIX: .post1

jobs:
  modify:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install wheel and pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install wheel pip-tools

      - name: Download latest wheel for the package
        run: |
          # native Linux platform
          pip download --no-deps --only-binary=:all: pyqt6 --dest wheels
          # non-Linux platforms
          for platform in win_amd64 macosx_10_14_universal2 manylinux_2_28_aarch64; do
            pip download --no-deps --platform $platform --only-binary=:all: pyqt6 --dest wheels
          done

      - name: Unpack the wheels
        run: |
          mkdir unpacked_wheels
          for wheel in wheels/*.whl; do
            unzip $wheel -d unpacked_wheels/$(basename $wheel .whl)
          done

      - name: Remove Qt6 dependency from wheels and rename the package, and tweak metadata
        run: |
          for metafile in unpacked_wheels/*/*.dist-info/METADATA; do
            sed -i '/^Requires-Dist: PyQt6-Qt6 .*/d' $metafile
            sed -i 's/^Name: PyQt6/Name: pyqt6-without-qt/' $metafile
            sed -i 's/^Version: \([[:alnum:].]*\)/Version: \1'$POST_RELEASE_SUFFIX'/' $metafile
            sed -i 's|^Project-Url: .*|Project-Url: homepage, https://github.com/maresb/pyqt6-without-qt|' $metafile
            sed -i 's|^Author-Email: .*|Author-Email: Ben Mares <services-pyqt6-without-qt@tensorial.com>\n\n\# Patched PyQt6 to remove Qt dependency\n\nSee \<https://github.com/maresb/pyqt6-without-qt\>|' $metafile
          done

      - name: Rename the package directories to pyqt6_without_qt and add POST_RELEASE_SUFFIX
        run: |
          for dir in unpacked_wheels/*; do
            mv $dir unpacked_wheels/$(basename $dir | sed 's/PyQt6-\([^-]*\)-\(.*\)/pyqt6_without_qt-\1'$POST_RELEASE_SUFFIX'-\2/')
          done
          for dir in unpacked_wheels/*/PyQt6; do
            mv $dir $(echo $dir | sed 's|PyQt6|pyqt6_without_qt|')
          done
          for dir in unpacked_wheels/*/*.dist-info; do
            mv $dir $(echo $dir | sed 's|PyQt6-\(.*\)\.dist-info|pyqt6_without_qt-\1'$POST_RELEASE_SUFFIX'.dist-info|')
          done

      - name: Repack the wheels
        run: |
          mkdir modified_wheels
          for dir in unpacked_wheels/*; do
            python -m wheel pack $dir -d modified_wheels
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: modified_wheels
          path: modified_wheels

  publish:
    needs: modify
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Download modified wheels
        uses: actions/download-artifact@v4
        with:
          name: modified_wheels
          path: dist

      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.8.14
